# Generated by Django 2.1.7 on 2019-03-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
