# Generated by Django 2.1.7 on 2019-03-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportsystem', '0005_post_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postmedia',
            field=models.ImageField(default='uploadedimages/None/no.img.jpg', upload_to='uploadedimages/'),
        ),
    ]
