# Generated by Django 2.1.7 on 2019-03-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportsystem', '0006_auto_20190316_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='company',
        ),
    ]
