# Generated by Django 2.1.7 on 2019-03-21 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supportsystem', '0008_auto_20190321_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supportsystem.Company'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supportsystem.Role'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
