# Generated by Django 2.1.7 on 2019-03-21 23:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supportsystem', '0009_auto_20190321_2330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtendedUser',
            new_name='ExtendedUserProfile',
        ),
    ]
